apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookingmicroservice
  labels:
    app: booking-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: booking-microservice
  template:
    metadata:
      labels:
        app:  booking-microservice
    spec:
      containers:
      - name: booking-microservice
        image: amarcs721992/booking-microservice:0.0.1-SNAPSHOT
        command: ["/bin/sh"]
        args: ["-c", "sleep 10000 && echo Sleep expired > /dev/termination-log"]
        ports:
        - containerPort: 80
 